// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkwnixkmakzvpgtwenbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrd25peGttYWt6dnBndHdlbmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NzIyNTksImV4cCI6MjA2NjE0ODI1OX0.xbYmivygTJpUmlkxRmeH3ompqLBJ-CURFwLesqaSgow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);